apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
- ingress-patch.yaml
images:
- name: acft-thegeauxpro-com
  newName: docker.io/bgautrea/acft
  newTag: sha-d149fd4
